/-
Copyright (c) 2024 ImportGraph Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ImportGraph Contributors
-/
module

public import Lean.Environment
public import Lean.CoreM
import Lean.Meta.Instances
import Lean.AuxRecursor
import Lean.ProjFns
import Lean.Meta.Match.MatcherInfo

open Lean Meta

/-!
# Common Filtering Logic for Dependency Graphs

Shared filtering utilities used by TypeDeps and ProofDeps graphs to identify
and filter mechanical/compiler-generated declarations.

Provides tiered filtering:
- **Exhaustive**: Includes everything except strictly internal compiler details.
- **Standard**: Filters auxiliary, mechanical, and generated declarations (default).
- **Mathematical**: Optional tier that also filters ubiquitous boilerplate (Eq, rfl, etc.).
-/

namespace Lean.Environment

/-- Filtering tiers for dependency graphs -/
public inductive FilterTier where
  | exhaustive   -- Include everything possible
  | standard     -- Filter auxiliary/generated/mechanical (default)
  | mathematical -- Filter ubiquitous boilerplate (Eq, rfl, etc.)
  deriving Inhabited, BEq

/-- 
Ubiquitous constants that create noise in mathematical graphs.
These are primarily filtered in the `mathematical` tier.
-/
def ubiquitousConstants : NameSet := 
  [`Eq, `rfl, `HEq, `id, `Unit, `True, `False, `And, `Or, `Not,
   `Nat, `Int, `String, `Char, `Bool, `List, `Option, `Sum,
   `Exists, `Subsingleton, `Decidable, `Inhabited, `Nonempty,
   `PUnit, `PTrue, `PFalse, `PLift, `ULift,
   `Add, `Mul, `Neg, `Inv, `Div, `Sub, `HMul, `HAdd, `HSub, `HDiv, `HPow,
   `LE, `LT, `GE, `GT, `HLE, `HLT, `HGE, `HGT,
   `OfNat, `OfNat.ofNat, `BEq, `LawfulBEq,
   `Lean.Parser.Tactic.next, `Lean.Parser.Tactic.done
  ].foldl (fun acc n => acc.insert n) ∅

/--
Determine if a constant name represents a mechanical/compiler-generated declaration.
-/
public def isMechanicalDeclaration (name : Name) : Bool :=
  match name with
  | .str _ "eq_def" => true
  | .str _ "sizeOf_spec" => true
  | .str _ "ctorIdx" => true
  | .str _ suffix => 
    (suffix.startsWith "eq_" && (suffix.drop 3).all Char.isDigit && suffix.length > 3) ||
    suffix == "_ctorIdx" ||
    suffix == "_sunsafe" ||
    suffix == "_cstage1" ||
    suffix == "_cstage2"
  | _ => false

/--
Get the "parent" declaration for a mechanical/auto-generated declaration.
-/
public def getParentDeclaration (env : Environment) (name : Name) : Name :=
  if let some info := env.find? name then
    match info with
    | .ctorInfo val => val.induct
    | .recInfo val => val.name.getPrefix
    | _ => 
      match name with
      | .str parent "eq_def" => parent
      | .str parent "sizeOf_spec" => parent
      | .str parent "ctorIdx" => parent
      | .str parent "_ctorIdx" => parent
      | .str parent suffix =>
        if suffix.startsWith "eq_" && (suffix.drop 3).all Char.isDigit && suffix.length > 3 then
          parent
        else
          name
      | _ => name
  else
    name

/--
Detect if a name is likely a typeclass instance.
-/
public def isLikelyInstance (name : Name) : Bool :=
  let s := name.toString
  s.startsWith "inst" || (s.splitOn ".inst").length > 1

/-- Check if a constant should be included in dependency graphs based on tier. -/
public def shouldIncludeConstant (env : Environment) (name : Name) 
    (tier : FilterTier := .standard) (includeInstances : Bool := false) : CoreM Bool := do
  
  -- Always filter internal details in all tiers
  if name.isInternalDetail then return false
  
  match tier with
  | .exhaustive => return true
  
  | .standard =>
    if isMechanicalDeclaration name then return false
    
    if let some info := env.find? name then
      match info with
      | .ctorInfo _ | .recInfo _ => return false
      | _ => pure ()
    
    if isAuxRecursor env name || isNoConfusion env name || 
       isProjectionFn env name || isMatcherCore env name then
      return false
      
    if !includeInstances && isLikelyInstance name then
      return false
      
    return true
    
  | .mathematical =>
    -- Inline the standard checks to avoid recursion/termination issues
    if isMechanicalDeclaration name then return false
    
    if let some info := env.find? name then
      match info with
      | .ctorInfo _ | .recInfo _ => return false
      | _ => pure ()
    
    if isAuxRecursor env name || isNoConfusion env name || 
       isProjectionFn env name || isMatcherCore env name then
      return false
      
    -- Mathematical tier specific filters
    if ubiquitousConstants.contains name then return false
    if isLikelyInstance name then return false
      
    return true

/-- Check if a name is an auto-generated helper lemma. -/
private def isAutoGeneratedLemma (name : Name) : Bool :=
  let str := name.toString
  str.endsWith ".inj" || str.endsWith ".injEq" || str.endsWith ".sizeOf_spec" ||
  str.endsWith ".rec" || str.endsWith ".recOn" || str.endsWith ".casesOn" ||
  str.endsWith ".brecOn" || str.endsWith ".noConfusion" || str.endsWith ".below" ||
  str.endsWith ".ibelow"

/-- Check if a constant should be included in proof dependency graphs. -/
public def shouldIncludeConstantInProofDeps (env : Environment) (name : Name) 
    (tier : FilterTier := .standard) (includeInstances : Bool := false) : CoreM Bool := do
  
  let generalInclude ← shouldIncludeConstant env name tier includeInstances
  if !generalInclude then return false
  
  if isAutoGeneratedLemma name then return false
  
  if let some info := env.find? name then
    match info with
    | .inductInfo _ | .opaqueInfo _ | .quotInfo _ => return false
    | .axiomInfo _ => return true
    | _ => return true
  else
    return false

/--
Apply transitive closure when filtering dependencies.
-/
public def applyTransitiveClosure (env : Environment) (deps : Array Name) 
    (tier : FilterTier := .standard) (includeInstances : Bool := false) : CoreM (Array Name) := do
  let mut result : Array Name := #[]
  let mut seen : NameSet := {}
  
  for dep in deps do
    let shouldInclude ← shouldIncludeConstant env dep tier includeInstances
    if shouldInclude then
      if !seen.contains dep then
        result := result.push dep
        seen := seen.insert dep
    else
      let parent := getParentDeclaration env dep
      if parent != dep && env.contains parent then
        let parentOk ← shouldIncludeConstant env parent tier includeInstances
        if parentOk && !seen.contains parent then
          result := result.push parent
          seen := seen.insert parent
  
  return result

/--
Apply transitive closure specifically for proof dependency graphs.
-/
public def applyTransitiveClosureForProofDeps (env : Environment) (deps : Array Name) 
    (tier : FilterTier := .standard) (includeInstances : Bool := false) : CoreM (Array Name) := do
  let mut result : Array Name := #[]
  let mut seen : NameSet := {}
  
  let rec findIncludableDeps (dep : Name) (visited : NameSet) (depth : Nat) : CoreM (Array Name) := do
    if depth = 0 || visited.contains dep then return #[]
    
    let shouldInclude ← shouldIncludeConstantInProofDeps env dep tier includeInstances
    if shouldInclude then return #[dep]
    
    let newVisited := visited.insert dep
    let mut subResult : Array Name := #[]
    
    if let some info := env.find? dep then
      let subDeps := match info with
      | .thmInfo val => val.value.getUsedConstants
      | .defnInfo val => val.value.getUsedConstants
      | _ => #[]
      
      if depth > 0 then
        for subDep in subDeps do
          let subIncludable ← findIncludableDeps subDep newVisited (depth - 1)
          subResult := subResult ++ subIncludable
    
    return subResult
  termination_by depth
  
  for dep in deps do
    let includableDeps ← findIncludableDeps dep {} 50
    for includableDep in includableDeps do
      if !seen.contains includableDep then
        result := result.push includableDep
        seen := seen.insert includableDep
  
  return result

end Lean.Environment
